FROM python:3
WORKDIR /app

RUN apt-get -qq update && \
    apt-get -qq install jq vim
RUN pip install yq prance[osv,icu,cli]

COPY . .

#RUN pip install -r requirements.txt 

CMD ["./swagger-k8s-crd-codegen.py"]
