apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: workbenchappspecs.ndslabs.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ndslabs.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                key:
                  type: string
                label:
                  type: string
                maintainer:
                  type: string
                info:
                  type: string
                logo:
                  type: string
                image:
                  type: object
                  properties:
                    registry:
                      type: string
                    name:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
                display:
                  type: string
                access:
                  type: string
                description:
                  type: string
                depends:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      required:
                        type: boolean
                      shareConfig:
                        type: boolean
                config:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      label:
                        type: string
                      canOverride:
                        type: boolean
                      isPassword:
                        type: boolean
                command:
                  type: string
                args:
                  type: array
                  items:
                    type: string
                ports:
                  type: array
                  items:
                    type: object
                    properties:
                      port:
                        type: integer
                      protocol:
                        type: string
                repositories:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                      type:
                        type: string
                developerEnvironment:
                  type: string
                volumeMounts:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mountPath:
                        type: string
                readinessProbe:
                  type: object
                  properties:
                    type:
                      type: string
                    path:
                      type: string
                    port:
                      type: integer
                    initialDelay:
                      type: integer
                    timeout:
                      type: integer
                resourceLimits:
                  type: object
                  properties:
                    cpuMax:
                      type: string
                    cpuDefault:
                      type: string
                    memMax:
                      type: string
                    memDefault:
                      type: string
                tags:
                  type: array
                  items:
                    type: string
            
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: workbenchappspecs
    # singular name to be used as an alias on the CLI and for display
    singular: workbenchappspec
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: WorkbenchAppSpec
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - workbenchspec
    - workbenchspecs
    - wbappspec
    - wbappspecs
    - appspec
    - appspecs
    - wbspec
    - wbspecs
    - spec
    - specs
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: workbenchuserapps.ndslabs.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ndslabs.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                key:
                  type: string
                name:
                  type: string
                status:
                  type: string
                action:
                  type: string
                createdTime:
                  type: integer
                updateTime:
                  type: integer
                secure:
                  type: boolean
                services:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      stack:
                        type: string
                      service:
                        type: string
                      status:
                        type: string
                      statusMessage:
                        type: array
                        items:
                          type: string
                      createdTime:
                        type: integer
                      updateTime:
                        type: integer
                      developerEnvironment:
                        type: string
                      config:
                        type: object
                        additionalProperties:
                          type: string
                        default: {}
                      readinessProbe:
                        type: object
                        properties:
                          type:
                            type: string
                          path:
                            type: string
                          port:
                            type: integer
                          initialDelay:
                            type: integer
                          timeout:
                            type: integer
                      statusMessages:
                        type: array
                        items:
                          type: string
                      resourceLimits:
                        type: object
                        properties:
                          cpuMax:
                            type: string
                          cpuDefault:
                            type: string
                          memMax:
                            type: string
                          memDefault:
                            type: string
                      imageTag:
                        type: string
                      internalIP:
                        type: string
                      volumeMounts:
                        type: object
                        additionalProperties:
                          type: string
                        default: {}
                      endpoints:
                        type: array
                        items:
                          type: object
                          properties:
                            path:
                              type: string
                            host:
                              type: string
                            port:
                              type: integer
                            nodePort:
                              type: integer
                            protocol:
                              type: string
                            url:
                              type: string

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: workbenchuserapps
    # singular name to be used as an alias on the CLI and for display
    singular: workbenchuserapp
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: WorkbenchUserApp
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - workbenchapp
    - workbenchapps
    - wbuserapp
    - wbuserapps
    - userapp
    - userapps
    - wbapp
    - wbapps
    - app
    - apps
